export const home = (req, res) => res.render("home");
export const search = (req, res) => res.render("serach");
export const join = (req, res) => res.render("join");
export const login = (req, res) => res.render("login");
export const logout = (req, res) => res.render("logout");
export const user = (req, res) => res.render("user");
export const user_detail = (req, res) => res.render("user_detail");
export const edit_profile = (req, res) => res.render("edit_profile");
export const change_password = (req, res) => res.render("change_password");
