export const home = (req, res) => res.send("Home");
export const search = (req, res) => res.send("Search");
export const join = (req, res) => res.send("join");
export const login = (req, res) => res.send("login");
export const logout = (req, res) => res.send("logout");
export const user = (req, res) => res.send("user");
export const user_detail = (req, res) => res.send("user_detail");
export const edit_profile = (req, res) => res.send("edit_profile");
export const change_password = (req, res) => res.send("change_password");
